### ISSUE TITLE
AWS4-HMAC-SHA256 in eu-central-1

### ISSUE THREAD

**Issue by vodafon** [refile/refile#164]
Versions:
aws-sdk-1.27.0
refile-0.5.3

Bucket region: Frankfurt (eu-central-1)

Get error:
```
AWS::S3::Errors::InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:366:in `return_or_raise'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:467:in `client_request'
	from (eval):3:in `put_object'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/aws-sdk-1.27.0/lib/aws/s3/s3_object.rb:1715:in `write_with_put_object'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/aws-sdk-1.27.0/lib/aws/s3/s3_object.rb:607:in `write'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/refile-0.5.3/lib/refile/backend/s3.rb:55:in `upload'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/refile-0.5.3/lib/refile/backend_macros.rb:31:in `block (2 levels) in verify_uploadable'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/refile-0.5.3/lib/refile/attacher.rb:107:in `download'
	from /Users/tot/.rvm/gems/ruby-2.1.2@rails4/gems/refile-0.5.3/lib/refile/attachment.rb:74:in `block (2 levels) in attachment'
```

Similar issue in paperclip https://github.com/thoughtbot/paperclip/issues/1691

I try this config:
```ruby
require "refile/backend/s3"

aws = {
  access_key_id: "XXX",
  secret_access_key: "YYY",
  bucket: "bucket",
  region: 'eu-central-1', 
  s3_signature_version: :v4
}
Refile.cache = Refile::Backend::S3.new(max_size: 10.megabytes, prefix: "cache", **aws)
Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)

```
But get same error.

**Comment by jnicklas** [comment]
This isn't really related to Refile. You'll have to ask Amazon how to make this work.
