### ISSUE TITLE
S3 upload works correctly, but retrieval crashes

### ISSUE THREAD

**Issue by johannesboyne** [refile/refile#171]
Hey Folks,

I am running mad, the upload to s3 is working 100% fine, thus I assume the credentials are right (full access rights for testing). But, retrieving the file fails with the following error code.
Does anyone got a clue what I am missing?

Thanks a lot for every answer!

```
I, [2015-03-03T10:20:23.085123 #7685]  INFO -- : Started GET "/attachments/store/fill/1920/500/c3d47a0353cc64741af26dbdebb63abe8754a7fd9a9b9e23d2e62c85274b/title_image" for 91.66.81.252 at 2015-03-03 10:20:23 +0000
I, [2015-03-03T10:20:23.176153 #7685]  INFO -- : [AWS S3 400 0.055258 0 retries] head_object(:bucket_name=>"cp-image-uploads",:key=>"store/c3d47a0353cc64741af26dbdebb63abe8754a7fd9a9b9e23d2e62c85274b") AWS::S3::Errors::BadRequest AWS::S3::Errors::BadRequest

E, [2015-03-03T10:20:23.176402 #7685] ERROR -- : Refile::App: Error -> AWS::S3::Errors::BadRequest
E, [2015-03-03T10:20:23.176535 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/core/client.rb:375:in `return_or_raise'
E, [2015-03-03T10:20:23.176567 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/core/client.rb:476:in `client_request'
E, [2015-03-03T10:20:23.176593 #7685] ERROR -- : Refile::App: (eval):3:in `head_object'
E, [2015-03-03T10:20:23.176617 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/s3/s3_object.rb:296:in `head'
E, [2015-03-03T10:20:23.176669 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/s3/s3_object.rb:273:in `exists?'
E, [2015-03-03T10:20:23.176693 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/backend/s3.rb:115:in `exists?'
E, [2015-03-03T10:20:23.176718 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/backend_macros.rb:11:in `block (2 levels) in verify_id'
E, [2015-03-03T10:20:23.176742 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/file.rb:53:in `exists?'
E, [2015-03-03T10:20:23.176766 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/app.rb:113:in `file'
E, [2015-03-03T10:20:23.176790 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/app.rb:52:in `block in <class:App>'
E, [2015-03-03T10:20:23.176814 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
E, [2015-03-03T10:20:23.176838 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
E, [2015-03-03T10:20:23.176862 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
E, [2015-03-03T10:20:23.176886 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
E, [2015-03-03T10:20:23.176909 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
E, [2015-03-03T10:20:23.176934 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
E, [2015-03-03T10:20:23.176957 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
E, [2015-03-03T10:20:23.176980 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
E, [2015-03-03T10:20:23.177004 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
E, [2015-03-03T10:20:23.177043 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
E, [2015-03-03T10:20:23.177068 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
E, [2015-03-03T10:20:23.177095 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
E, [2015-03-03T10:20:23.177119 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
E, [2015-03-03T10:20:23.177142 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
E, [2015-03-03T10:20:23.177165 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
E, [2015-03-03T10:20:23.177190 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
E, [2015-03-03T10:20:23.177214 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
E, [2015-03-03T10:20:23.177237 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
E, [2015-03-03T10:20:23.177260 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
E, [2015-03-03T10:20:23.177284 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
E, [2015-03-03T10:20:23.177309 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
E, [2015-03-03T10:20:23.177332 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
E, [2015-03-03T10:20:23.177355 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
E, [2015-03-03T10:20:23.177393 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/refile-0.5.3/lib/refile/custom_logger.rb:14:in `call'
E, [2015-03-03T10:20:23.177415 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2015-03-03T10:20:23.177446 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2015-03-03T10:20:23.177468 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
E, [2015-03-03T10:20:23.177490 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
E, [2015-03-03T10:20:23.177514 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
E, [2015-03-03T10:20:23.177548 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
E, [2015-03-03T10:20:23.177570 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
E, [2015-03-03T10:20:23.177597 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
E, [2015-03-03T10:20:23.177619 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
E, [2015-03-03T10:20:23.177642 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
E, [2015-03-03T10:20:23.177671 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
E, [2015-03-03T10:20:23.177695 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
E, [2015-03-03T10:20:23.177717 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
E, [2015-03-03T10:20:23.177740 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
E, [2015-03-03T10:20:23.177765 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
E, [2015-03-03T10:20:23.177787 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-tracker-0.3.0/lib/rack/tracker.rb:29:in `call'
E, [2015-03-03T10:20:23.177818 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
E, [2015-03-03T10:20:23.177840 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
E, [2015-03-03T10:20:23.177877 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
E, [2015-03-03T10:20:23.177911 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
E, [2015-03-03T10:20:23.177934 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
E, [2015-03-03T10:20:23.177956 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
E, [2015-03-03T10:20:23.177980 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
E, [2015-03-03T10:20:23.178004 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
E, [2015-03-03T10:20:23.178028 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
E, [2015-03-03T10:20:23.178052 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
E, [2015-03-03T10:20:23.178075 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
E, [2015-03-03T10:20:23.178100 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
E, [2015-03-03T10:20:23.178123 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
E, [2015-03-03T10:20:23.178147 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
E, [2015-03-03T10:20:23.178171 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
E, [2015-03-03T10:20:23.178208 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
E, [2015-03-03T10:20:23.178233 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
E, [2015-03-03T10:20:23.178261 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
E, [2015-03-03T10:20:23.178286 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
E, [2015-03-03T10:20:23.178309 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
E, [2015-03-03T10:20:23.178347 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
E, [2015-03-03T10:20:23.178371 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
E, [2015-03-03T10:20:23.178398 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
E, [2015-03-03T10:20:23.178422 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
E, [2015-03-03T10:20:23.178446 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
E, [2015-03-03T10:20:23.180103 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
E, [2015-03-03T10:20:23.180148 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
E, [2015-03-03T10:20:23.180182 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
E, [2015-03-03T10:20:23.180207 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
E, [2015-03-03T10:20:23.180241 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
E, [2015-03-03T10:20:23.180265 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
E, [2015-03-03T10:20:23.180288 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84:in `call'
E, [2015-03-03T10:20:23.180312 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
E, [2015-03-03T10:20:23.180335 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
E, [2015-03-03T10:20:23.180358 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
E, [2015-03-03T10:20:23.180391 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
E, [2015-03-03T10:20:23.180414 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
E, [2015-03-03T10:20:23.180437 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
E, [2015-03-03T10:20:23.180475 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
E, [2015-03-03T10:20:23.180498 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
E, [2015-03-03T10:20:23.180521 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/bin/unicorn_rails:23:in `load'
E, [2015-03-03T10:20:23.180551 #7685] ERROR -- : Refile::App: /home/deploy/.bundler/platform/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
I, [2015-03-03T10:20:23.181339 #7685]  INFO -- : Refile::App: [2015-03-03 10:20:23 +0000] GET "/store/fill/1920/500/c3d47a0353cc64741af26dbdebb63abe8754a7fd9a9b9e23d2e62c85274b/title_image" 500 94.8ms
```

**Comment by rossta** [comment]
Can you access the file through your browser or curl at `"<your aws bucket host>/store/c3d47a0353cc64741af26dbdebb63abe8754a7fd9a9b9e23d2e62c85274b"`?

**Comment by johannesboyne** [comment]
Yes, that's possible: https://s3.eu-central-1.amazonaws.com/cp-image-uploads/store/19241d0ebc828d11ebaee9983d93fe0d2c4d1f425c36283fab5f475d8d68

**Comment by johannesboyne** [comment]
Anyone having an other idea? I would really like to continue using refile, it works 99.99% like expected and I seriously enjoy the API design of it!

**Comment by jerryclinesmith** [comment]
I was getting the exact same behavior - it was because I had the 2.0 aws-sdk gem.  It needs to be set to "< 2" if you're using refile 0.5.  Also make sure you are reading the README for tag 0.5.5 (or whatever Refile version you're on) because the README is different than the Master branch.

**Comment by johannesboyne** [comment]
Thanks @jerryclinesmith you're right! It works with the `< 2` 2.0 aws-sdk gem.
