### ISSUE TITLE
NameError: uninitialized constant Refile::ImageProcessor

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile#225]
file name: config/initializers/custom_image_processor.rb
```
class CustomImageProcessor < Refile::ImageProcessor
  def fill_watermark(img, width, height, gravity = "Center")
    ...
  end

  def fit_watermark(img, width, height, gravity = "Center")
    ...
  end
end

[:fill, :fit, :limit, :pad, :convert, :fill_watermark, :fit_watermark].each do |name|
  Refile.processor(name, CustomImageProcessor.new(name))
end
```

error:
```
NameError: uninitialized constant Refile::ImageProcessor
/Users/meduser/sites/city/config/initializers/custom_image_processor.rb:1:in `<top (required)>'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:592:in `each'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `instance_exec'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `run'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `each'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `run_initializers'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:136:in `initialize!'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/meduser/sites/city/config/environment.rb:5:in `<top (required)>'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:103:in `require_environment!'
/Users/meduser/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/Users/meduser/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/meduser/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => movies:update => environment
(See full trace by running task with --trace)
```

**Comment by janko-m** [comment]
You need to `require "refile/image_processing"`.

**Comment by eddiefisher** [comment]
I'm added this line and get next error:
```[Refile] image processing has been extracted into a separate gem, see https://github.com/refile/refile-mini_magick```
than I'm added in Gemfile ```gem 'refile-mini_magick'``` but got new error
```Could not find gem 'refile-mini_magick (>= 0) ruby' in the gems available on this machine.```
than I'm change on ```gem 'refile-mini_magick', github: 'refile/refile-mini_magick'```
and gem was installed, but I'm got error again
```[Refile] image processing has been extracted into a separate gem, see https://github.com/refile/refile-mini_magick```

**Comment by jnicklas** [comment]
If you're running off master you need to do something like this:

``` ruby
gem 'refile', require: 'refile/rails', github: 'refile/refile'
gem 'refile-mini_magick', github: 'refile/refile-mini_magick'
```

You should not be requiring `refile/image_processing`, as this has been extracted into the separate `refile-mini_magick` repo, which will soon be released as a gem.
