### ISSUE TITLE
require `refile` outside of rails

### ISSUE THREAD

**Issue by asiniy** [refile/refile#238]
I'm writing my pure ruby application, so, I want to include a models of my existing rails app. So, I've got a trouble.

``` ruby
# just .rb file in the root of rails app
models_path = File.expand_path('app/models')
Dir[models_path + '/*.rb'].each { |file| require file } # require each model file
```

When I require my models, I get (predictably!) this exception

``` ruby
dynamic_matchers.rb:26:in `method_missing': undefined method `attachment' for ShopPhoto (call 'ShopPhoto.connection' to establish a connection)
```

I've tried both

``` ruby
require 'refile'

models_path = File.expand_path('app/models')
Dir[models_path + '/*.rb'].each { |file| require file } # require each model file
# => the same error
```

and

``` ruby
require 'refile/rails'

models_path = File.expand_path('app/models')
Dir[models_path + '/*.rb'].each { |file| require file } # require each model file
# => lib/refile/rails.rb:6:in `<module:Refile>': uninitialized constant Refile::Rails (NameError)
```

My Gemfile is standard:

``` ruby
gem 'mini_magick'
gem 'refile', require: 'refile/rails'
gem 'refile-mini_magick'
```

ruby -v `2.2.1`, refile -v `0.5.5`

How can I require my models to `.rb` files?

Thanks in advance,
Alex

**Comment by asiniy** [comment]
Got it!

``` ruby
require 'refile/attachment'
require 'refile/attachment/active_record'

models_path = File.expand_path('app/models')
Dir[models_path + '/*.rb'].each { |file| require file } # require each model file
# => THAT'S WORKED!!!
```
