### ISSUE TITLE
Error on Heroku Deploy

### ISSUE THREAD

**Issue by matiasmasca** [refile/refile#293]
My gem is set in this way:
gem 'refile', require: "refile/rails", git: 'https://github.com/refile/refile.git', branch: 'master'

In local development all was fine, but when I tried to deploy on Heroku, I receive this errors:
https://travis-ci.org/matiasmasca/Novedades/builds/70123784 (LINE 522).

       Could not detect rake tasks

       ensure you can run `$ bundle exec rake -P` against your app with no environment variables present

       and using the production group of your Gemfile.

       rake aborted!

       SyntaxError: /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/bundler/gems/refile-0dc2072a9002/lib/refile.rb:248: syntax error, unexpected ','

       ... Refile.mount_point, filename:, format: nil, host: Refile.ho...

       ...                               ^

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/bundler/gems/refile-0dc2072a9002/lib/refile.rb:248: Can't assign to nil

       ..._point, filename:, format: nil, host: Refile.host)

       ...                               ^

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/bundler/gems/refile-0dc2072a9002/lib/refile.rb:248: syntax error, unexpected ')', expecting keyword_end

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/bundler/gems/refile-0dc2072a9002/lib/refile.rb:361: syntax error, unexpected keyword_end, expecting end-of-input

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/bundler/gems/refile-0dc2072a9002/lib/refile/rails.rb:1:in `<top (required)>'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/config/application.rb:7:in `<top (required)>'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/Rakefile:4:in `require'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/Rakefile:4:in `<top (required)>'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

       /tmp/build_d2fed5eb563d51be49ebf204bdd98ae0/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'

       vendor/bundle/bin/rake:16:in `load'

       vendor/bundle/bin/rake:16:in `<main>'

**Comment by matiasmasca** [comment]
Apparently, It was the version of Ruby in Heroku. I changed it to 2.2.0 and it works.

https://travis-ci.org/matiasmasca/Novedades/jobs/70316870
