### ISSUE TITLE
Weird error that I only get when running in production mode

### ISSUE THREAD

**Issue by hydrozen** [refile/refile#346]
I’ve got my uploads working fine locally and in my tests, but when I try it on production it blows up when I try to upload a file (the file is not required and it doesnt blow up if I don’t upload a file).

I get the following error:

```
NoMethodError (undefined method `object' for nil:NilClass):
  app/interactors/update_auction.rb:11:in `call'
  app/controllers/admin/auctions_controller.rb:26:in `update'
```

and the code of update_auction.rb looks like this. Any ideas what could be the problem?

```ruby
class UpdateAuction
  include Interactor

  attr_accessor :auction
  attr_accessor :params

  def call
    self.params = context.params
    self.auction = context.auction = Auction.find(context.params[:id])
    auction.assign_attributes(auction_params)
    context.fail! && return unless auction.valid?
    auction.geocode if auction.geocodable?
    save_auction
  end

  private

  def auction_params
    params.require(:auction).permit(
      :title, :slug, :body, :date, :address, :address_for_geocoding,
      :short_description, :start_time, :pdf, :image, :catalog, :published,
      :remove_image, :remove_pdf, :remove_catalog
    )
  end

  def save_auction
    if auction.save
      BroadcastAuctionWorker.perform_async(auction.id) if auction.broadcastable?
    else
      context.fail!
    end
  end
end
```

**Comment by hydrozen** [comment]
Found the problem, nevermind.
