### ISSUE TITLE
simple_form issue

### ISSUE THREAD

**Issue by sobrinho** [refile/refile#421]
rails 3.2.22
simple form 2.1.3

```
<%= f.input :file, as: :attachment %>
```

```
undefined method `merge_wrapper_options' for #<SimpleForm::Inputs::AttachmentInput:0x007fc2b0e542a8>

refile (0.6.2) lib/refile/simple_form.rb:8:in `input'
simple_form (2.1.3) lib/simple_form/components/label_input.rb:11:in `label_input'
simple_form (2.1.3) lib/simple_form/wrappers/many.rb:29:in `block in render'
simple_form (2.1.3) lib/simple_form/wrappers/many.rb:27:in `each'
simple_form (2.1.3) lib/simple_form/wrappers/many.rb:27:in `render'
simple_form (2.1.3) lib/simple_form/wrappers/root.rb:15:in `render'
simple_form (2.1.3) lib/simple_form/form_builder.rb:117:in `input'
app/views/imports/_form.html.erb:14:in `block (2 levels) in _app_views_imports__form_html_erb__1822506517190200501_70237088127880'
```

**Comment by sobrinho** [comment]
http://stackoverflow.com/questions/26303091/undefined-method-merge-wrapper-options

Fixed by creating a custom input implementing the merge_wrapper_options:

``` ruby
class AttachmentInput < SimpleForm::Inputs::AttachmentInput
  def merge_wrapper_options(options, wrapper_options)
    if wrapper_options
      options.merge(wrapper_options) do |_, oldval, newval|
        if Array === oldval
          oldval + Array(newval)
        end
      end
    else
      options
    end
  end
end
```

Makes sense to add support to latest compatible simple form with rails 3.2?

**Comment by sobrinho** [comment]
We are not going to support legacy simple form versions anymore.

This was added to simple form 3.1 and we are already in simple form 3.5.

Closing.
