### ISSUE TITLE
Is thread safety a requirement?

### ISSUE THREAD

**Issue by relaxdiego** [refile/refile#459]
I'm trying to get Refile to work with Ceph but found that the Fog provider doesn't work with it. Also, fog-radosgw only supports provisioning but not usage. I found that aws-s3 works well with Ceph and plan on wrapping that with a Refile provider and then later on submit it as part of this Github org. However, it's not thread safe. For my purposes, that's not a problem since I can just use the process forking feature of Puma to run my Rails app but I wasn't sure if that's OK with the rest of the community.

**Comment by jnicklas** [comment]
Which part do you think is not thread safe?

**Comment by relaxdiego** [comment]
Here's how it's used:

```ruby
AWS::S3::Base.establish_connection!(
        :server            => 'objects.dreamhost.com',
        :use_ssl           => true,
        :access_key_id     => 'my-access-key',
        :secret_access_key => 'my-secret-key'
)

AWS::S3::Service.buckets.each do |bucket|
        puts "#{bucket.name}\t#{bucket.creation_date}"
end

AWS::S3::Bucket.create('my-new-bucket')
```

More at: http://docs.ceph.com/docs/hammer/radosgw/s3/ruby/

**Comment by jnicklas** [comment]
I'm still not following which part you think is not thread safe?

**Comment by jnicklas** [comment]
Is it the AWS::S3 gem, or something in Refile? Which part in particular?

**Comment by relaxdiego** [comment]
@jnicklas sorry for not being clear. I meant that the aws-s3 gem was not thread safe. I wanted to wrap that with a `refile-ceph` gem/provider but then it would not be thread safe (because aws-s3 is not thread safe) and I wanted to check if that's alright if i submitted it anyway.

**Comment by jnicklas** [comment]
You know we already have an S3 gem, right? https://github.com/refile/refile-s3 The underlying API is the same, so if it works with aws-s3 it should work with aws-sdk as well.

**Comment by relaxdiego** [comment]
Yes, I have and that works fine when using S3, but not with Ceph. And it's not the fault of `refile-s3` but simply because `aws-sdk` works with the API in a way that Ceph doesn't understand:

```ruby
2.3.0 :011 >   Aws.config[:ssl_ca_bundle] = 'config/certs.pem'
 => "config/certs.pem"

2.3.0 :014 > c = Aws::S3::Resource.new endpoint: "https://<REDACTED PRIVATE URL>", access_key_id: "BDCVIRVEWSGN9NWVW1QL", secret_access_key: "550sEvjtxBFuPz10L8xWASrSkMZ3gmc6aykzLlCb", region: "us-east-1", http_wire_trace: true
 => #<Aws::S3::Resource>

2.3.0 :015 > c.buckets.each{|b| p b}
opening connection to <REDACTED PRIVATE URL>:443...
opened
starting SSL for <REDACTED PRIVATE URL>:443...
SSL established
<- "GET / HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.2.29 ruby/2.3.0 x86_64-darwin15 resources\r\nX-Amz-Date: 20160323T202845Z\r\nHost: <REDACTED PRIVATE URL>\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=BDCVIRVEWSGN9NWVW1QL/20160323/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=2499cfb578cd0d45385a9e58c1e91e6650321552094e6f5a3fe8c0411c47c1e3\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Server: nginx/1.6.3\r\n"
-> "Date: Wed, 23 Mar 2016 20:28:42 GMT\r\n"
-> "Content-Type: application/xml\r\n"
-> "Content-Length: 81\r\n"
-> "Connection: keep-alive\r\n"
-> "x-amz-request-id: tx000000000000000011afe-0056f2fc7a-259f5-default\r\n"
-> "Accept-Ranges: bytes\r\n"
-> "\r\n"
reading 81 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>InvalidArgument</Code></Error>"
read 81 bytes
Conn keep-alive
Aws::S3::Errors::InvalidArgument:
        from /path/to/gems/aws-sdk-core-2.2.29/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/seahorse/client/request.rb:70:in `send_request'
        from /path/to/gems/aws-sdk-core-2.2.29/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /path/to/gems/aws-sdk-resources-2.2.29/lib/aws-sdk-resources/request.rb:24:in `call'
        from /path/to/gems/aws-sdk-resources-2.2.29/lib/aws-sdk-resources/operations.rb:127:in `all_batches'
        from /path/to/gems/aws-sdk-resources-2.2.29/lib/aws-sdk-resources/collection.rb:18:in `each'
        from /path/to/gems/aws-sdk-resources-2.2.29/lib/aws-sdk-resources/collection.rb:18:in `each'
        from (irb):15
        from /path/to/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :016 >
```

**Comment by relaxdiego** [comment]
Turns out I may not need to do this. I downgraded `aws-sdk` to 2.1.x and tried it in irb and looks like it's working. I'll go ahead and see if everything's good when I used that with `refile-s3`. In the meantime, closing this issue. Thanks!

**Comment by relaxdiego** [comment]
Downgrading `aws-sdk` to 2.1.x works! I was able to connect and upload files after I used the following config:

```ruby
require "refile-s3"

Aws.config[:ssl_ca_bundle] = "path/to/ceph/cert" # Necessary if the ceph server uses a self-signed cert

Refile.configure do |c|
  opts = {
    endpoint: "https://url.of.ceph.instance",
    access_key_id: "accesskeyhere",
    secret_access_key: "secretkeyhere",
    bucket: "mybucket",
    region: "us-east-1",  # required by aws-sdk but doesn't really mater to ceph
    force_path_style: true
  }

  c.cache = Refile::S3.new(prefix: "cache", **opts)
  c.store = Refile::S3.new(prefix: "store", **opts)
end
```

Thanks @jnicklas and team for this excellent gem!
