### ISSUE TITLE
(undefined method `id' for nil:NilClass). Does not respond to 'read'

### ISSUE THREAD

**Issue by chevinbrown** [refile/refile#470]
I'm getting this error when trying to save a record with an attachment:

```
ArgumentError - does not respond to `read`.:
  refile (0.2.5) lib/refile.rb:48:in `block in verify_uploadable'
  refile (0.2.5) lib/refile.rb:46:in `verify_uploadable'
  refile (0.2.5) lib/refile/backend/file_system.rb:15:in `upload'
  refile (0.2.5) lib/refile/attachment.rb:35:in `file='
  refile (0.2.5) lib/refile/attachment.rb:93:in `block in attachment'
  activemodel (5.0.0.beta3) lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
  activemodel (5.0.0.beta3) lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
  activemodel (5.0.0.beta3) lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
  activerecord (5.0.0.beta3) lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
  activemodel (5.0.0.beta3) lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
  activerecord (5.0.0.beta3) lib/active_record/core.rb:310:in `initialize'
  activerecord (5.0.0.beta3) lib/active_record/inheritance.rb:65:in `new'
  app/controllers/knowledges_controller.rb:46:in `create'
  actionpack (5.0.0.beta3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0.beta3) lib/abstract_controller/base.rb:183:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/rescue.rb:27:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0.beta3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0.beta3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0.beta3) lib/abstract_controller/base.rb:128:in `process'
  actionview (5.0.0.beta3) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.9.9.2) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
  actionpack (5.0.0.beta3) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:724:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:12:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  actionview (5.0.0.beta3) lib/action_view/digestor.rb:12:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0.beta3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (5.0.0.beta3) lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
  rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.beta3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
  rack-mini-profiler (0.9.9.2) lib/mini_profiler/profiler.rb:281:in `call'
  railties (5.0.0.beta3) lib/rails/engine.rb:522:in `call'
  puma (3.4.0) lib/puma/configuration.rb:224:in `call'
  puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
  puma (3.4.0) lib/puma/server.rb:406:in `process_client'
  puma (3.4.0) lib/puma/server.rb:271:in `block in run'
  puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'

Started GET "/__meta_request/a686b2ba-6455-4ca2-856b-4ba0fec69f3a.json" for 10.0.2.2 at 2016-04-25 14:41:56 -0500
Started POST "/__better_errors/007029a60a9d2584/variables" for 10.0.2.2 at 2016-04-25 14:41:56 -0500

NoMethodError (undefined method `id' for nil:NilClass):
```

No idea why this is happening...I'm using refile and refile-postgres.  Is refile-postgres necessary?

**Comment by krists** [comment]
@chevinbrown Your refile version looks very outdated. Current one is 0.6.2

**Comment by chevinbrown** [comment]
@krists, I must be getting it from rubygems, not github? Is there a rails 5 branch?

**Comment by krists** [comment]
@chevinbrown Have you tried `bundle update refile refile-postgres`?

**Comment by chevinbrown** [comment]
@krists, just confirmed...fixed with bundle update (all). Somehow in adding the 'refile' gem, my bundle didn't include some sinatra requisites.
