### ISSUE TITLE
Rspec + Refile

### ISSUE THREAD

**Issue by kerensei** [refile/refile#495]
I am using the latest version of the refile gem to upload images to AWS and it's working fine. when I try to test my app with rspec i get this error:

**$ rspec**
/usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.4.3/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize': missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)

so I tried to export the region and still no luck:

**$ export  AWS_REGION=us-east-1**
/usr/local/rvm/gems/ruby-2.3.0/gems/refile-s3-0.2.0/lib/refile/s3.rb:47:in `initialize': Credentials not found (Refile::S3CredentialsError)

**I have been using Figaro gem to store my credentials in initializers/refile.rb**
require "refile/s3"
require 'refile/simple_form'
aws = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: ENV['AWS_REGION'],
  bucket: ENV['AWS_BUCKET']
}
Refile.cache = Refile::S3.new(prefix: "cache", **aws)
Refile.store = Refile::S3.new(prefix: "store", **aws)

Any ideas? thanks

**Comment by kerensei** [comment]
needed to add:
if Rails.env.production?
  aws = {
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    region: ENV['AWS_REGION'],
    bucket: ENV['AWS_BUCKET']
  }
  
  Refile.cache = Refile::S3.new(prefix: "cache", **aws)
  Refile.store = Refile::S3.new(prefix: "store", **aws)
end
