### ISSUE TITLE
Can't modify frozen hash on model `destroy`

### ISSUE THREAD

**Issue by arcreative** [refile/refile#513]
Having trouble deleting models with attachments on them--It just fails with the following trace:

```
   (0.3ms)  BEGIN
  SQL (0.4ms)  DELETE FROM "app_revisions" WHERE "app_revisions"."id" = $1  [["id", 8]]
   (0.3ms)  ROLLBACK
RuntimeError: Can't modify frozen hash
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_set/builder.rb:45:in `[]='
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_set.rb:51:in `write_from_user'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/write.rb:50:in `write_attribute_with_type_cast'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/write.rb:32:in `write_attribute'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/write.rb:20:in `__temp__6696c656f59646='
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/refile-0.2.5/lib/refile/attachment.rb:23:in `id='
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/refile-0.2.5/lib/refile/attachment.rb:64:in `delete!'
	from /Users/adam/.rvm/gems/ruby-2.3.1/gems/refile-0.2.5/lib/refile/attachment/active_record.rb:21:in `block in attachment'
```

Is this a compatibility issue with Rails 5 maybe?  Looks like it's trying to write a temporary attribute after the model has been destroyed?

Simplified model is as follows:

```rb
class AppRevision < ApplicationRecord
  validates_presence_of :app, :file, :version

  belongs_to :app

  attachment :file
end
```

Would appreciate any help or insight!

**Comment by dcrec1** [comment]
Were you able to fix this?

**Comment by arcreative** [comment]
No.  I haven't really looked at it lately--the project I'm using refile for has been on my back burner for a bit...

**Comment by sobrinho** [comment]
Likely outdated refile (0.2.5 as your backtrace).

Give it a shot on latest release or even with the master, if you can replicate that, feel free to reopen the issue, thanks! <3
